# tlp_custom.conf

# TLP profiles to use when automatic switching is enabled
# (TLP_AUTO_SWITCH=1 or 2):
#   PRF=performance, BAL=balanced, SAV=power-saver.
# Default: PRF (AC power), BAL (battery power)

TLP_AUTO_SWITCH=2

TLP_PROFILE_AC=PRF

TLP_PROFILE_BAT=SAV
